# 例外処理



## 例外処理



### エラーを投げる

式はエラーの種類を表す値、プロトコルErrorに準拠する必要がある

```swift
throw 式
```

エラーを投げる関数は引数の直後に`throws`を記述して表す

```swift
func myFunc(num:Int) throws -> Int
```

エラーを投げるイニシャライザも定義できる

```swift
init(num:Int) throws
```



### エラーを投げる関数の呼び出し方

1. `try`を使って呼び出すが、それ以上何もしない
2. do-catch文を使い、`try`を使った呼び出しでエラーが起きたら捕まえる
3. `try?`を使って呼び出す
4. `try!`を使って呼び出す



### do-catch構文

```swift
do {
   // tryを用いた関数の呼び出しなど
} catch エラー種類 where節 {
   // 「エラー種類」「where節」はどっちも省略可能
} catch {
   // 条件を指定しないcatch節は最後に置く
   // 投げられるエラーの値はerrorという定数で参照できる
}
```



### try?とtry!

これらはdo-catch文と組み合わせる必要がない

* try?

  戻り値がオプショナルとなり、エラーが起きたらnilを返す

  この方法はエラーの原因や種類に応じた細かい対応ができない

  ```swift
  if let bin = try? myFunc(){      }
  ```

  戻り値がない関数は、`Void?`を返すので、nilかどうかで、エラーの有無を判断する

  ```swift
  if (try? myFunc()) != nil {      }
  ```

* try!

  エラーが発生しない限り、通常の関数と同様に扱う

  エラーが発生したら、実行時エラーとなる

  



























